sudo: required

language: scala

services:
    - docker


script:
  - docker run -it --rm 
    -v $HOME:/var/home/ 
    -v $(pwd):/src 
    frol2103/activator:1.3.12 
    /opt/activator/bin/activator clean test

