sudo: required

language: scala

services:
    - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0


script:
  - docker run -it --rm 
    -v $HOME:/var/home/ 
    -v $(pwd):/src 
    frol2103/activator:1.3.12 
    /opt/activator/bin/activator clean compile

  - docker run -it --rm 
    -v $HOME:/var/home/ 
    -v $(pwd):/src 
    frol2103/activator:1.3.12 
    /opt/activator/bin/activator test

  - docker-compose up -d

  - docker run -it --rm 
    -v $HOME:/var/home/ 
    -v $(pwd):/src 
    --network playrestauthenticator_default
    frol2103/activator:1.3.12 
    /opt/activator/bin/activator clean it:test

notifications:
  email:
    on_success: always
    on_failure: always 
