version: '2'

services:
  db:
    image: mongo

  app:
    image: docker.centran.in:5000/activator:1.3.12
    volumes:
      - .:/src
      - ~:/var/home
    ports:
      - 9000:9000
    command: activator test
    stdin_open: true
