version: '2'

services:
  db:
    image: mongo

  app:
    image: frol2103/activator:1.3.12
    volumes:
      - .:/src
      - ~:/var/home
    ports:
      - 9000:9000
    command: activator run
    stdin_open: true

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025
      - 8025

  ldap:
    image: dinkel/openldap
    ports:
      - 389
    environment:
      - SLAPD_PASSWORD=mysecretpassword
      - SLAPD_DOMAIN=ldap.example.org
