version: '2'

services:
  db:
    image: mongo

  app:
    image: frol2103/activator:1.3.12
    volumes:
      - .:/src
      - ~:/var/home
    ports:
      - 9000:9000
    command: activator run
    stdin_open: true
